[package]
name = "csf_cg_binary_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csf_cg_lib_test = { path = "../csf_cg_lib_test" }