[package]
name = "cg_fusion_binary_test"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cg_fusion_lib_test = { path = "../cg_fusion_lib_test" }