# impl config file in TOML format to configure included or excluded impl items of
# specific user defined types in respectively from challenge.
# file structure:
# include_impl_items = [include_item_1, include_item_2]
# exclude_impl_items = [exclude_item_1, exclude_item_2]
#
# If the name of the impl item is ambiguous (e.g. push(), next(), etc.), add as much
# information to the name as is required to make the name unique including the name of
# the user defined type:
# path::to::module::of::impl_block_of_user_defined_type_name::user_defined_type_name::impl_item_name.
#
# Usage of wildcard '*' for impl item is possible, if at least the name of the user defined type is
# given. E.g. 'user_defined_type_name::*' will include or exclude all impl items of
# 'user_defined_type_name'.
#
# If in conflict with other impl options, the 'include' option always wins.
include_impl_items = ["impl<T:Copy+Clone+Default,constX:usize,constY:usize,constN:usize> MyMap2D<T,X,Y,N>::set", "x", "y"]
exclude_impl_items = []
